title: "Stephen Covell"
email: contact@stephencovell.dev
description: >- # this means to ignore newlines until "baseurl:"
  Hello! I'm a Nottingham Trent University Undergraduate Student! I have created this website with MLH.
baseurl: "/" 
url: "stephencovell.github.io" 
twitter_username: elitesteveuk
github_username:  stephencovell

sass:
  sass_dir: _sass

icon: ./assets/img/icon.jpg
